[package]
name = "symba"
version = "0.1.0"
edition = "2021"
authors = ["Ranjeeth Mahankali <ranjeethmahankali@gmail.com>"]
description = "A library with tools for working with symbolic expressions."
readme = "README.md"
repository = "https://github.com/ranjeethmahankali/symba"
license = "GPL-3.0-only"
keywords = ["symbolic", "expressions", "math", "algebra"]
categories = ["mathematics"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
lazy_static = "1.4"
inkwell = { version = "0.4", features = ["llvm14-0"] }
