[package]
name = "eiche"
version = "0.2.1"
edition = "2021"
authors = ["Ranjeeth Mahankali <ranjeethmahankali@gmail.com>"]
description = "A library with tools for working with symbolic expressions."
readme = "README.md"
repository = "https://github.com/ranjeethmahankali/eiche"
license = "GPL-3.0-only"
keywords = ["symbolic", "expressions", "math", "algebra", "tree"]
categories = ["mathematics"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
inkwell = { version = "0.4", features = ["llvm14-0"], optional = true }
inari = { version = "2.0", optional = true }

[features]
llvm-jit = ["dep:inkwell"]
inari-intervals = ["dep:inari"]
